# INSTALL NECESSARY PACKAGES

In [1]:
# %conda install -c conda-forge install statsbombpy mplsoccer pandas numpy
# %pip install statsbombpy mplsoccer pandas numpy

# IMPORTING LIBRARIES

In [2]:
from statsbombpy import sb
import pandas as pd

# View competitions
competitions = sb.competitions()
competitions.head()

/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

# AGGREGATE ALL EVENTS FROM 1 SEASON IN 1 LEAGUE

In [3]:
# Picking Engligh Premier League(competition_id=2), La Liga(competition_id=11), Serie A(competition_id=12), Ligue 1(competition_id=7), Bundesliga(competition_id=12)
# Season 2015/2016(season_id=27)

leagues = [2, 7, 9, 11, 12]
matches = pd.DataFrame()
for league in leagues: 
    matches = pd.concat([matches, sb.matches(competition_id=league, season_id=27)], ignore_index=True)

matches.head()

/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3754217,2015-09-19,11:45:00.000,2,0,available,scheduled,2025-12-16T17:01:18.696515,2021-06-13T16:17:31.694,6,...,Portugal,577,Arsène Wenger,None,1949-10-22,78,France,1.1.0,2,2
1,3754117,2015-12-13,12:30:00.000,0,2,available,scheduled,2025-12-16T17:04:24.176407,2021-06-13T16:17:31.694,16,...,France,577,Arsène Wenger,None,1949-10-22,78,France,1.1.0,2,2
2,3754296,2015-12-21,19:00:00.000,2,1,available,scheduled,2025-12-17T11:59:35.059270,2021-06-13T16:17:31.694,17,...,France,733,Manuel Luis Pellegrini Ripamonti,Manuel Pellegrini,1953-09-16,45,Chile,1.1.0,2,2
3,3753983,2015-10-31,14:00:00.000,0,3,available,scheduled,2025-12-16T17:02:24.849544,2021-06-13T16:17:31.694,11,...,England,577,Arsène Wenger,None,1949-10-22,78,France,1.1.0,2,2
4,3754160,2015-12-05,14:00:00.000,3,1,available,scheduled,2025-12-16T17:03:25.661537,2021-06-13T16:17:31.694,15,...,France,561,Sam Allardyce,None,1954-10-19,68,England,1.1.0,2,2

In [4]:
# Pull event data for a match
match_id = matches.match_id.iloc[0]

events = sb.events(match_id=match_id)
events.head()
# events.shape

/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Chelsea,33,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Arsenal,1,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Chelsea,33,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Arsenal,1,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Arsenal,1,00:00:00.000,Half Start,NaN

In [5]:
# Pulling all matches in season into one dataframe
all_events = []

for match_id in matches.match_id:
    try:
        match_events = sb.events(match_id=match_id)
        match_events['match_id'] = match_id
        all_events.append(match_events)

    except Exception as e:
        print(f"Failed match {match_id}: {e}")

events_df = pd.concat(all_events, ignore_index=True)

events_df.head()

# takes ~32 mins to run

/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/nanakwamekankam/miniconda3/envs/xg_env/lib/python3.10/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,dribble_no_touch,player_off_permanent,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
events_df.shape

(5436699, 120)

# SAVE LOCALLY

In [7]:
events_df.to_csv('~/Desktop/Football_Stats/xG/datasets/raw/Big5_statsbomb_events.csv', index=False)

In [8]:
# Parquet if you prefer
# events_df.to_parquet('~/Desktop/Football_Stats/xG/statsbomb_events.parquet')